# Generated by Django 4.2.7 on 2023-12-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_choice_image_review_alter_choice_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image_review',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
