# Generated by Django 4.2.7 on 2023-12-08 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_choice_image_review_imagereview_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagereview',
            name='choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='image_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.imagereview'),
        ),
        migrations.AlterField(
            model_name='imagereview',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.poll'),
        ),
    ]
